name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ">=11"
    - name: install
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: build
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: build
    - name: test
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test
